bradenmacdonald/s3-lite-client

README.md
client.ts
deno.jsonc
deps-tests.ts
deps.ts
integration.ts

* Updates to Deno std library v0.170.0
* Implements `copyObject`

Version 0.3.0: Implement copyObject, bump Deno std library version

---

README.md
client.test.ts
client.ts

* People would get a "redirect" error if using authenticated requests with the `s3.amazonaws.com` endpoint, as reported in #3. I've changed the README in the example to use the region-specific endpoint that will fix this problem, and I've updated the code to provide a more helpful error message.
* Fixed #6 - The default port number should never be included in the Host header.

Fix issues with host names

---

integration.ts
signing.test.ts
signing.ts
xml-parser.ts

Fixes the other issue reported in #12 which wasn't fixed by #15.
Amazon's URI encoding algorithm is different than the `encodeURIComponent` available to us in JavaScript, so we have to write our own, following [the AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html).
This includes expanded test cases.

fix: some special characters in URLs were not being handled correctly

---

client.ts

When the ListV2 API returns multiple prefixes, it returns them in separate `<CommonPrefix>` nodes. Currently `listObjectsGrouped` only looks at the first instance of `<CommonPrefix>`. This PR changes it to yield entries from all of them.
Aside: initially I thought this might be a bug in minio, but the team sorted me out! https://github.com/minio/minio-js/issues/1176#issuecomment-1605855907

Handle multiple CommonPrefix nodes in listObjectsGrouped

---

deps-tests.ts
deps.ts

Pulls in the latest version of the deno standard library.

chore: bump to std@0.215.0

---

.github/workflows/run-tests.yml

Fixes this warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: `actions/checkout@v2`. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

chore: upgrade deprecated github checkout action

---

README.md
client.ts
integration.ts

This PR introduces new functionalities to the client. The added methods allow for checking if a bucket exists, creating a new bucket, and removing an existing bucket in the client. These methods are `bucketExists`, `makeBucket`, and `removeBucket` respectively.

Added bucket operations to supported functionality

---

.github/workflows/publish.yml
.github/workflows/run-tests.yml
client.ts
integration.ts
mod.ts

This runs the integration tests using [Bun](https://bun.sh/) as well as Deno.
Running the tests with Node.js is not feasible at the moment due to TypeScript usage and issues like https://github.com/TypeStrong/ts-node/issues/1997

Support more JavaScript runtimes

---

errors.ts
mod.ts

I hadn't figured out how to get a JSDoc comment on the `S3Errors` namespace, but I figured it out now I think.
I also renamed `DenoS3LiteClientError` to `S3Error` since you can use this with many different runtimes now. Old name is kept as an alias to avoid breaking changes.

docs: fix JSdoc for errors, rename error base class to S3Error

---

client.test.ts
deps-tests.ts
deps.ts
helpers.test.ts
integration.ts
signing.test.ts
transform-chunk-sizes.test.ts
transform-chunk-sizes.ts

These files don't provide any value now that Deno/JSR lets you specify dependency versions in `deno.jsonc`

Remove 'deps.ts' and 'deps-test.ts'

---

README.md
client.ts
integration.ts

This PR:
* Closes #23 by adding a `metadata` option to `copyObject()` (now you can replace the metadata when copying an object)
* Updates the README to clarify how to set custom headers, ACLs, and other metadata. See #34.
* Adds stronger typing for some metadata fields like `x-amz-acl`

Allow replacing metadata when copying an object, document metadata better

---

client.ts
mod.ts

to make it possible to refer to the type of the constructor arguments from the outside without any "hacks".

feat: export all types from client with S3 prefix

---

object-uploader.ts

When trying to do a multipart upload with customer provided encryption keys, the upload fails with "The multipart upload initiate requested encryption. Subsequent part requests must include the appropriate encryption parameters."
This PR includes the required headers in individual part uploads if specified

specify tagalong headers for multipart uploads

---

.github/workflows/publish.yml
.github/workflows/run-tests.yml
README.md

CI was running with Deno 1.x, but it's now time to use Deno 2. No meaningful changes to the code; just formatting fixes.

Run tests with deno 2, fix formatting issues it finds

---

.github/workflows/run-tests.yml
README.md
client.test.ts
deno.jsonc
helpers.test.ts
integration.ts
signing.test.ts
transform-chunk-sizes.test.ts
transform-chunk-sizes.ts

This library had one runtime dependency, which was [`Buffer` from `@std/io/buffer`](https://jsr.io/@std/io/doc/~/Buffer). But it seems like [that is never going to be stabilized](https://github.com/denoland/std/issues/5003), so I was considering switching to the very similar (but more complicated) [`Buffer` from `@std/streams/buffer`](https://jsr.io/@std/streams/doc/~/Buffer). But then I realized I could refactor this to not need any `Buffer` class at all 😎.
Now we are using the stable 1.x version of the JS Standard Library for test assertions, and have no runtime dependencies.

Remove runtime dependency (Buffer), bump stdlib version used in tests

---

client.test.ts
client.ts

Fixes #48 
Tested example:
```ts
const client = new S3Client({
endPoint: "127.0.0.1",
port: 54321,
useSSL: false,
region: "local",
pathPrefix: "/storage/v1/s3",
accessKey: "paste from output of supabase start",
secretKey: "paste from output of supabase start",
});
await client.makeBucket("test");
const keys = await Array.fromAsync(client.listObjects({ bucketName: "test" }), (entry) => entry.key);
console.log(keys);
```

feat: allow specifying pathPrefix for supabase compatibility

---

client.ts

If the stat object command allows headers to be added to it, then the exists command should allow those same headers. 
The exact use case I'm seeing is with Tigris data storage, where to get a consistent read I need to add the header 'x-tigris-cas': 'true' or else I will get a cached result back.

include headers option on exists check

---

client.ts
deno.jsonc
integration.ts

Encourage people to use full URLs in `endPoint` when initializing.

docs: mark 'useSSL' and 'port' as deprecated

---

client.ts
helpers.ts
object-uploader.ts
signing.ts

[These changes in TypeScript 5.7](https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/#typedarrays-are-now-generic-over-arraybufferlike) and perhaps also the [related changes in 5.9](https://devblogs.microsoft.com/typescript/announcing-typescript-5-9/#lib.d.ts-changes) cause a bunch of errors when type checking this repo.
Example:
```
TS2345 [ERROR]: Argument of type 'Uint8Array<ArrayBufferLike>' is not assignable to parameter of type 'BufferSource'.
Type 'Uint8Array<ArrayBufferLike>' is not assignable to type 'ArrayBufferView<ArrayBuffer>'.
Types of property 'buffer' are incompatible.
Type 'ArrayBufferLike' is not assignable to type 'ArrayBuffer'.
Type 'SharedArrayBuffer' is missing the following properties from type 'ArrayBuffer': resizable, resize, detached, transfer, …
```

fix: compatibility with std lib changes in TypeScript 5.7 & 5.9

---

.github/workflows/check-bundle-size.yml
.github/workflows/publish.yml
.github/workflows/run-tests.yml

So we'll use deno instead of node to publish it.
Error details:
```
Run npx jsr publish
npm warn exec The following package was not found and will be installed: jsr@0.13.5
Downloading JSR release binary...
Download completed
Check file:///home/runner/work/s3-lite-client/s3-lite-client/mod.ts
TS2322 [ERROR]: Type 'Uint8Array<ArrayBufferLike>' is not assignable to type 'string | Uint8Array<ArrayBuffer> | undefined'.
Type 'Uint8Array<ArrayBufferLike>' is not assignable to type 'Uint8Array<ArrayBuffer>'.
Type 'ArrayBufferLike' is not assignable to type 'ArrayBuffer'.
Type 'SharedArrayBuffer' is missing the following properties from type 'ArrayBuffer': resizable, resize, detached, transfer, transferToFixedLength
payload = new TextEncoder().encode(payload);
~~~~~~~
at …
```

fix: JSR publish via npx failed due to outdated @types/node
